swagger: '2.0'
info:
  version: '0.1.0'
  title: my simple api v.2
  description: An API to rate movies
host: localhost:9191
basePath: /movies-api
schemes:
  - http
paths:
  /movies:
    get:
      description: get the list of all movies
      operationId: getMovies
      produces:
        - application/json
      parameters:
        - name: keyword
          in: query
          required: false
          type: string
        - name: Authorization
          in: header
          required: true
          type: string
        - name: page
          in: query
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Movie'
  /movies/{movieId}:
    get:
      description: get all ratings for a specific movie
      operationId: getRatingsByMovie
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - name: movieId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Rating'
    post:
      description: rate a movie
      operationId: addRating
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - name: movieId
          in: path
          required: true
          type: string
        - name: rating
          in: body
          required: true
          schema:
              $ref: '#/definitions/Rating'
      responses:
        '201':
          description: created
          schema:
            $ref: '#/definitions/Rating'
  /movies/{movieId}/avg:
    get:
      description: get the average rating for a specific movie
      operationId: getAvgRatingByMovie
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - name: movieId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: object
  /movies/my-ratings:
    get:
      description: get personal ratings
      operationId: getPersonalRatings
      produces:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Rating'
    put:
      description: update a rating
      operationId: updateRating
      consumes:
        - application/json
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - name: ratingId
          in: query
          required: true
          type: string
        - name: rating
          in: body
          required: true
          schema:
              $ref: '#/definitions/Rating'
      responses:
        '200':
          description: updated
          schema:
            type: object
    delete:
      description: delete a rating
      operationId: removeRating
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
        - name: ratingId
          in: query
          required: true
          type: string
      responses:
        '200':
          description: removed
          schema:
            type: object
definitions:
  Movie:
    type: object
    properties:
      movie_id:
        type: integer
      title:
        type: string
      description:
        type: string
      director:
        type: string
  User:
    type: object
    properties:
      email:
        type: string
  Rating:
    type: object
    properties:
      rating_id:
        type: integer
      user_id:
        type: string
      movie_id:
        type: string
      rating:
        type: integer
      description:
        type: string

