version: '3'
services:
    auth_server:
        build: ../docker-images/spring-boot/authentication
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql_users:3306/users?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin
        ports:
            - "8080:8080"
        labels:
            - "traefik.enable=true"
            - "traefik.ports=8080"
            - "traefik.http.routers.auth_server.entrypoints=web"
            - "traefik.http.routers.auth_server.rule=PathPrefix(`/api/users/`)"
    movies_server:
        build: ../docker-images/spring-boot/movies
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql_movies:3306/movies?autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin
        ports:
            - "9090:9090"
        labels:
            - "traefik.enable=true"
            - "traefik.ports=9090"
            - "traefik.http.routers.movies_server.entrypoints=web"
            - "traefik.http.routers.movies_server.rule=PathPrefix(`/api/movies`)"
    mysql_users:
        build: ../docker-images/mysql/users
        environment: 
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=users
        ports:
            - "3306:3306" 
    mysql_movies:
        build: ../docker-images/mysql/movies
        environment: 
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=movies
        ports:
            - "3307:3306"  
    phpmyadmin:
        build: ../docker-images/phpmyadmin
        environment:
            - MYSQL_USER=admin
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - "6060:80"
        links:
            - mysql_users:db_users
            - mysql_movies:db_movies
    traefik:
        image: "traefik:v2.0.0"
        command:
            - "--providers.docker"
            - "--api.insecure=true"
            - "--accessLog=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8181:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
           


      
   