version: '3'
services:
    
    mysql:
        build: ../docker-images/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=admin
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_DATABASE=users
        ports:
            - "3306:3306"  
    phpmyadmin:
        build: ../docker-images/phpmyadmin
        environment:
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - "6060:80"
        links:
            - mysql:db
   